--- 

- hosts: localhost
  name: Example K8S Module
  module_defaults:
    community.kubernetes.k8s:
      host: "{{ kube_api_url }}"
      validate_certs: no
      api_key: "{{ kube_api_key }}"

  tasks:

  - name: Create namespace
    community.kubernetes.k8s:
      name: openshift
      api_version: v1
      kind: Namespace
      state: present
